name: CI

on:
  push:
    branches:
      - main
      - wip
  pull_request:

jobs:
  test-gsd-parser:
    name: Run gsd-parser testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test -p gsd-parser

  check-profirust:
    name: Check profirust sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sudo apt-get install -y libudev-dev
      - run: RUSTFLAGS=-Dwarnings cargo check -p profirust --all-features --examples

  test-profirust:
    name: Run profirust testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sudo apt-get install -y libudev-dev
      - run: cargo test -p profirust

  test-gsdtool:
    name: Test-build gsdtool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build -p gsdtool

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rust-lang/rustfmt@v1
